version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: libdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: P@$$w0rd
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
